# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
   build:
      jobs:
         - build:
            context: 
               - personal_gh_releases

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: go mod download

      - run: 
         name: Create the artifacts directory
         command: mkdir -p /tmp/artifacts

      - run: 
         name: Install the Github release creator tool
         command: go get github.com/tcnksm/ghr
   
      - run:
         name: Run tests
         command: go test -v -race github.com/danesparza/icaltoday/data

      - run:
         name: Build AWS handler
         command: env GOOS=linux go build -ldflags "-X main.BuildVersion=1.0.$CIRCLE_BUILD_NUM -X main.CommitID=$CIRCLE_SHA1" -o icaltoday main.go

      - run:
         name: Package AWS handler
         command: zip icaltoday_handler.zip ./icaltoday

      - run:
         name: Push package to artifacts
         command: mv icaltoday_handler.zip /tmp/artifacts/

      # Indicate we have artifacts
      - store_artifacts:
          path: /tmp/artifacts

      - run: 
         name: Create a release on Github
         command: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME v1.0.$CIRCLE_BUILD_NUM /tmp/artifacts || true
